In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Datasets/Kaggle sber bank/processed_df.csv')

In [4]:
import torch

In [33]:
df

,Unnamed: 0,id,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc
0,0,1,43.0,27.00000,4.0,12.567592,1.83439,2716.784531,1.900844,6.543995,...,9,4,0,13,22,1,0,52,4,5850000
1,1,2,34.0,19.00000,3.0,12.567592,1.83439,2716.784531,1.900844,6.543995,...,15,3,0,15,29,1,10,66,14,6000000
2,2,3,43.0,29.00000,2.0,12.567592,1.83439,2716.784531,1.900844,6.543995,...,10,3,0,11,27,0,4,67,10,5700000
3,3,4,89.0,50.00000,9.0,12.567592,1.83439,2716.784531,1.900844,6.543995,...,11,2,1,4,4,0,0,26,3,13100000
4,4,5,77.0,77.00000,4.0,12.567592,1.83439,2716.784531,1.900844,6.543995,...,319,108,17,135,236,2,91,195,14,16331452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30466,30466,30469,44.0,27.00000,7.0,9.000000,1.00000,1975.000000,2.000000,6.000000,...,15,5,0,15,26,1,2,84,6,7400000
30467,30467,30470,86.0,59.00000,3.0,9.000000,2.00000,1935.000000,4.000000,10.000000,...,313,128,24,98,182,1,82,171,15,25000000
30468,30468,30471,45.0,34.03346,10.0,20.000000,1.00000,2716.784531,1.000000,1.000000,...,1,1,0,2,12,0,1,11,1,6970959
30469,30469,30472,64.0,32.00000,5.0,15.000000,1.00000,2003.000000,2.000000,11.000000,...,22,1,1,6,31,1,4,65,7,13500000
30470,30470,30473,43.0,28.00000,1.0,9.000000,1.00000,1968.000000,2.000000,6.000000,...,5,2,0,7,16,0,9,54,10,5600000

In [35]:
df.describe()

,Unnamed: 0,id,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc
count,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,3.047100e+04,30471.000000,30471.000000,...,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,30471.000000,3.047100e+04
mean,15235.000000,15237.917397,54.214269,34.325804,7.670782,12.561681,1.829404,2.911217e+03,1.906989,6.444755,...,32.058318,10.783860,1.771783,15.045552,30.251518,0.442421,8.648814,52.796593,5.987070,7.123035e+06
std,8796.364363,8796.501536,38.031487,46.487973,5.305390,5.595531,1.226642,1.148604e+05,0.705446,23.408951,...,73.465611,28.385679,5.418807,29.118668,47.347938,0.609269,20.580741,46.292660,4.889219,4.780111e+06
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+05
25%,7617.500000,7620.500000,38.000000,22.000000,3.000000,9.000000,1.000000,1.976000e+03,1.900844,5.000000,...,2.000000,1.000000,0.000000,2.000000,9.000000,0.000000,0.000000,11.000000,1.000000,4.740002e+06
50%,15235.000000,15238.000000,49.000000,34.033460,7.000000,12.567592,1.834390,2.014000e+03,1.900844,6.543995,...,8.000000,2.000000,0.000000,7.000000,16.000000,0.000000,2.000000,48.000000,5.000000,6.274411e+06
75%,22852.500000,22855.500000,63.000000,38.000000,11.000000,16.000000,1.834390,2.716785e+03,2.000000,8.000000,...,21.000000,5.000000,1.000000,12.000000,28.000000,1.000000,7.000000,76.000000,10.000000,8.300000e+06
max,30470.000000,30473.000000,5326.000000,7478.000000,77.000000,117.000000,6.000000,2.005201e+07,19.000000,2014.000000,...,377.000000,147.000000,30.000000,151.000000,250.000000,2.000000,106.000000,218.000000,21.000000,1.111111e+08

In [36]:
Features = df["full_sq"]
labels = df.iloc[:,-1:]

In [37]:
X_Train = torch.FloatTensor(Features.values)
y_train = torch.FloatTensor(labels.values)

In [38]:
X_Train

tensor([43., 34., 43.,  ..., 45., 64., 43.])

In [39]:
y_train

tensor([[ 5850000.],
        [ 6000000.],
        [ 5700000.],
        ...,
        [ 6970959.],
        [13500000.],
        [ 5600000.]])

In [40]:
X_Train.shape

torch.Size([30471])

In [41]:
linear = torch.nn.Linear(1,1)

In [42]:
loss_fun = torch.nn.MSELoss()

In [47]:
learning_rate = 0.001
optimizer = torch.optim.SGD(linear.parameters(), lr=learning_rate)

In [50]:
for epoch in range(200):
    y_pred = linear(X_Train)
    loss = loss_fun(y_pred, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
        
    if (epoch+1) % 5 == 0:
        print ('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 200, loss.item()))

RuntimeError: size mismatch, m1: [1 x 30471], m2: [1 x 1] at C:\Users\builder\AppData\Local\Temp\pip-req-build-9msmi1s9\aten\src\TH/generic/THTensorMath.cpp:197